using Carrigan.Core.Extensions;
using Carrigan.Core.Interfaces;
using Carrigan.SqlTools.Exceptions;
using Carrigan.SqlTools.Invocation;
using Carrigan.SqlTools.SqlGenerators;
using System.Data;
using System.Data.Common;
using System.Data.SqlTypes;
using System.Reflection;
using System.Transactions;
using System.Xml;
//IGNORE SPELLING: xml

namespace Carrigan.SqlTools.SqlServer;

/// <summary>
/// Provides command functionality used by <see cref="Commands"/> and <see cref="CommandsAsync"/>.
/// </summary>
internal static class CommandSharedMethods
{
    /// <summary>
    /// Builds a <see cref="DbCommand"/> instance.
    /// </summary>
    /// <param name="query">The SQL query generated by Carrigan.SqlTools.</param>
    /// <param name="connection">The connection.</param>
    /// <param name="transaction">The transaction (optional).</param>
    /// <returns>A configured <see cref="DbCommand"/> instance.</returns>
    public static DbCommand CreateCommand(SqlQuery query, DbConnection connection, DbTransaction? transaction = null)
    {
        DbCommand command = connection.CreateCommand();
        if (transaction != null)
        {
            command.Transaction = transaction;
        }
        command.CommandText = query.QueryText;
        command.CommandType = query.CommandType;
        command.Parameters.AddRange(query.GetParameterCollection().ToArray());

        return command;
    }

    /// <summary>
    /// Reads a single record field-by-field, performs type and property mapping, and returns a newly invoked instance.
    /// </summary>
    /// <param name="dataReader">The data reader positioned on the current record.</param>
    /// <returns>A new instance of <typeparamref name="T"/> populated with values from the current record.</returns>
    internal static T ReadRecord<T>(DbDataReader dataReader) where T : class, new()
    {
        ArgumentNullException.ThrowIfNull(dataReader);

        Dictionary<string, object?> rowData = [];
        string dataTypeName;
        for (int i = 0; i < dataReader.FieldCount; i++)
        {
            dataTypeName = dataReader.GetDataTypeName(i);
            if (dataReader.IsDBNull(i))
                rowData.Add(dataReader.GetName(i), DBNull.Value);
            else if (string.Equals(dataTypeName, "xml", StringComparison.OrdinalIgnoreCase))
                rowData.Add(dataReader.GetName(i), new SqlXml(XmlReader.Create(new StringReader(dataReader.GetString(i)))));
            else
                rowData.Add(dataReader.GetName(i), dataReader.GetValue(i));
        }
        return Invoker<T>.Invoke(rowData);
    }

    /// <summary>
    /// Performs field-level decryption, if necessary, and modifies the records in-place.
    /// </summary>
    /// <typeparam name="T">The object type of the records.</typeparam>
    /// <param name="results">The list of records to modify.</param>
    /// <param name="decrypters">The decrypter provider, or <see langword="null"/> when no decryption is required.</param>
    /// <exception cref="DecrypterNotProvided{T}">Thrown when one or more encrypted properties exist, but no decrypter provider is supplied.</exception>
    /// <exception cref="NoKeyVersionException{T}">Thrown when encrypted properties exist, but the type does not define a key-version property (for example, a property marked with <c>[KeyVersion]</c>).</exception>
    /// <exception cref="Exception">Thrown when encrypted properties contain values, but no matching decryption key can be found.</exception>
    internal static void DecryptFields<T>(List<T> results, IDecrypters? decrypters) where T : class, new()
    {
        int? decryptionVersion = 1;
        IEncryption? decrypter = null;
        if (ClientReflectorCache<T>.EncryptedProperties.Any())
        {
            if (decrypters is null)
                throw new DecrypterNotProvided<T>();

            _ = ClientReflectorCache<T>.KeyVersionProperty ?? throw new NoKeyVersionException<T>();
            foreach (T record in results)
            {
                decrypter = null;

                decryptionVersion = (int?)ClientReflectorCache<T>.KeyVersionProperty.GetValue(record);
                if (decryptionVersion is not null && decrypters.Keys.Contains(decryptionVersion.Value))
                {
                    decrypter = decrypters.Decrypter(decryptionVersion.Value);

                    foreach (PropertyInfo property in ClientReflectorCache<T>.EncryptedProperties)
                    {
                        string? value = property.GetValue(record)?.ToString();
                        if (value.IsNotNullOrWhiteSpace() && decrypter is not null)
                        {
                            value = decrypter.Decrypt(value);
                            property.SetValue(record, value);
                        }
                    }
                }

                if (decrypter is null)
                {
                    foreach (PropertyInfo property in ClientReflectorCache<T>.EncryptedProperties)
                    {
                        string? value = property.GetValue(record)?.ToString();
                        if (value.IsNotNullOrWhiteSpace())
                        {
                            throw new Exception($"No encryption key found for {ClientReflectorCache<T>.Type.Name}.{property.Name}");
                        }
                    }
                }
            }
        }
    }
}
