using Carrigan.SqlTools.Attributes;
using System.ComponentModel.DataAnnotations;
//IGNORE SPELLING: newid
namespace Carrigan.SqlTools.PostgreSql.IntegrationTests.Models;

[Identifier("ReturnModel")]
[Dialect(DialectEnum.PostgreSql)]
internal class ReturnModel
{
    [PrimaryKey]
    //Should be auto id
    public int Id1 { get; set; }

    [PrimaryKey]
    //Should default to newid()
    public Guid Id2 { get; set; }

    public int NotKey1 { get; set; }
    public int NotKey2 { get; set; }
    [Alias("NotKey3Alias")]
    public int NotKey3 { get; set; }

    //Should Default to the sql system date/time
    public DateTime DateTime { get; set; }

    //Should default to "Pending"
    public string? Status { get; set; } = null;

    //Should default to true
    public bool DeletedFlag { get; set; }

    // PostgreSQL table DDL (used by the fixture)
    internal static string CreateTableSql =>
        """
        CREATE EXTENSION IF NOT EXISTS pgcrypto;

        CREATE TABLE "ReturnModel"
        (
            "Id1" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            "Id2" uuid NOT NULL DEFAULT gen_random_uuid(),

            "NotKey1" integer NOT NULL,
            "NotKey2" integer NOT NULL,
            "NotKey3" integer NOT NULL,

            "DateTime" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,

            "Status" varchar(50) NOT NULL DEFAULT 'Pending',

            "DeletedFlag" boolean NOT NULL DEFAULT TRUE,

            CONSTRAINT "PK_ReturnModel" PRIMARY KEY ("Id1", "Id2")
        );
        """;
}
