using Carrigan.SqlTools.Exceptions;
using System.Data;
using Carrigan.Core.Extensions;

//IGNORE SPELLING: xml, unicode
namespace Carrigan.SqlTools.Types;

/// <summary>
/// Represents a strongly typed SQL Server type definition, including metadata such as
/// size, precision, scale, MAX indicators, and the corresponding SQL declaration string.
/// </summary>
/// <remarks>
/// <para>
/// This class provides a uniform, validated abstraction over SQL Server type metadata,
/// ensuring that SQL types generated by Carrigan.SqlTools are consistent, safe, and
/// compliant with SQL Server's size, precision, and scale rules.
/// </para>
/// <para>
/// A <see cref="SqlTypeDefinition"/> may be created in three ways:
/// <list type="bullet">
///   <item><description>
///     Automatically, when derived from a CLR type using <see cref="SqlTypeDefinition(object?)"/>
///     or <see cref="SqlTypeDefinition(Type)"/>.
///   </description></item>
///   <item><description>
///     Explicitly, by using one of the factory methods such as
///     <see cref="AsVarChar(int?)"/>, <see cref="AsDecimal(byte, byte)"/>,
///     <see cref="AsDateTime2(byte?)"/>, etc.
///   </description></item>
///   <item><description>
///     As an override applied via a <see cref="Attributes.SqlTypeAttribute"/>,
///     allowing model properties to specify custom SQL types.
///   </description></item>
/// </list>
/// </para>
/// <para>
/// All factory methods enforce SQL Server’s legal limits for length, precision, and scale.
/// Invalid combinations automatically raise a <see cref="SqlTypeArgumentOutOfRangeException"/>.
/// </para>
/// <para>
/// The resulting instance also computes a fully formatted SQL type declaration string
/// (e.g., <c>VARCHAR(50)</c>, <c>DATETIME2(3)</c>, <c>VARBINARY(MAX)</c>),
/// stored in <see cref="TypeDeclaration"/>, which is used when emitting CREATE TABLE,
/// ALTER TABLE, and parameter declarations.
/// </para>
/// </remarks>
public class SqlTypeDefinition
{
    //TODO: Document
    private const int LIMIT_FOR_ASCII = 8000;
    private const int LIMIT_FOR_UNICODE = 4000;
    private const int LIMIT_FOR_BYTE_ARRAY = 8000;
    /// <summary>
    /// Gets the SQL Server ADO.NET type associated with this definition.
    /// </summary>
    public SqlDbType Type { get; init; }

    /// <summary>
    /// Gets the maximum length for variable-length <see cref="SqlDbType"/> values, where applicable.
    /// For example, this is the length in characters for
    /// <see cref="SqlDbType.Char"/>, <see cref="SqlDbType.VarChar"/>,
    /// <see cref="SqlDbType.NChar"/>, and <see cref="SqlDbType.NVarChar"/>,
    /// or the length in bytes for <see cref="SqlDbType.Binary"/> and
    /// <see cref="SqlDbType.VarBinary"/>. A value of <c>null</c> indicates
    /// that no explicit size was specified.
    /// </summary>
    public int? Size { get; init; } = null;

    /// <summary>
    /// Gets the precision component for numeric or time-based <see cref="SqlDbType"/>s, where applicable.
    /// For <see cref="SqlDbType.Decimal"/>, this is the total number of digits.
    /// For <see cref="SqlDbType.Float"/>, this can represent the number of bits of precision.
    /// A value of <c>null</c> indicates that no explicit precision was specified.
    /// </summary>
    public byte? Precision { get; init; } = null;

    /// <summary>
    /// Gets the scale associated with this type, when applicable.
    /// For <see cref="SqlDbType.Decimal"/> this is the number
    /// of digits to the right of the decimal point.
    /// For <see cref="SqlDbType.Time"/>, <see cref="SqlDbType.DateTime2"/>, and
    /// <see cref="SqlDbType.DateTimeOffset"/>, this represents the fractional seconds precision
    /// (0–7), consistent with SqlParameters.
    /// A value of <c>null</c> indicates that no explicit scale was specified.
    /// </summary>
    public byte? Scale { get; init; } = null;

    /// <summary>
    /// Gets a value indicating whether the type uses the <c>MAX</c> length modifier
    /// (for example, <c>VARCHAR(MAX)</c>, <c>NVARCHAR(MAX)</c>, or <c>VARBINARY(MAX)</c>).
    /// Used with:
    /// <see cref="SqlDbType.VarChar"/>
    /// <see cref="SqlDbType.NVarChar"/>
    /// <see cref="SqlDbType.VarBinary"/>
    /// </summary>
    public bool UseMax { get; init; } = false;

    /// <summary>
    /// Gets the <see cref="SqlDbType"/> declaration string (for example, <c>INT</c>, <c>VARCHAR(50)</c>,
    /// <c>VARBINARY(MAX)</c>), including any size, precision, or scale arguments.
    /// </summary>
    public string TypeDeclaration { get; init; } = string.Empty;

    /// <summary>
    /// Initializes a new instance of the <see cref="SqlTypeDefinition"/> class.
    /// </summary>
    private SqlTypeDefinition()
    {
    }

    //TODO: Update documentation, unit test and code review for when the underlying type is char, string or byte[]
    /// <summary>
    /// Initializes a new instance of the <see cref="SqlTypeDefinition"/> class
    /// using the default <see cref="SqlDbType"/> mapping for the runtime type of the specified value.
    /// </summary>
    /// <param name="value">
    /// The value whose CLR type is used to determine the <see cref="SqlDbType"/>.
    /// </param>
    public SqlTypeDefinition(object? value)
    {
        Type = SqlTypeCache.GetSqlDbTypeFromValue(value);
        if (value is not null && value.GetUnderlyingType() == typeof(char))
        {
            TypeDeclaration = $"{ToSql(Type)}(1)";
        }
        else if (value is not null && value.GetUnderlyingType() == typeof(string))
        {
            TypeDeclaration = $"{ToSql(Type)}(MAX)";
        }
        else if (value is not null && value.GetUnderlyingType() == typeof(byte[]))
        {
            TypeDeclaration = $"{ToSql(Type)}(MAX)";
        }
        else
        {
            TypeDeclaration = ToSql(Type);
        }
    }

    //TODO: Update documentation, unit test and code review for when the underlying type is char or string
    /// <summary>
    /// Initializes a new instance of the <see cref="SqlTypeDefinition"/> class
    /// using the default <see cref="SqlDbType"/> mapping for the specified CLR <paramref name="type"/>.
    /// </summary>
    /// <param name="type">
    /// The CLR <see cref="Type"/> to use when determining the <see cref="SqlDbType"/>.
    /// </param>
    public SqlTypeDefinition(Type type)
    {
        Type = SqlTypeCache.GetSqlDbType(type);
        if (type.GetUnderlyingType() == typeof(char))
        {
            TypeDeclaration = $"{ToSql(Type)}(1)";
        }
        else if (type.GetUnderlyingType() == typeof(string))
        {
            TypeDeclaration = $"{ToSql(Type)}(MAX)";
        }
        else if (type.GetUnderlyingType() == typeof(byte[]))
        {
            TypeDeclaration = $"{ToSql(Type)}(MAX)";
        }
        else
        {
            TypeDeclaration = ToSql(Type);
        }
    }

    #region helper methods

    /// <summary>
    /// Validates that an <see cref="int"/> value lies within the specified range
    /// and throws an exception if it does not.
    /// </summary>
    /// <param name="type">
    /// The <see cref="SqlDbType"/> associated with the value, used only in the exception message.
    /// </param>
    /// <param name="name">
    /// The parameter name associated with the value, used only in the exception message.
    /// </param>
    /// <param name="value">The value to test.</param>
    /// <param name="min">The inclusive minimum allowed value.</param>
    /// <param name="max">The inclusive maximum allowed value.</param>
    /// <exception cref="SqlTypeArgumentOutOfRangeException">
    /// Thrown when <paramref name="value"/> is less than <paramref name="min"/> or greater than <paramref name="max"/>.
    /// </exception>
    private static void EnsureRange(SqlDbType type, string name, int value, int min, int max)
    {
        if (value < min || value > max)
            throw new SqlTypeArgumentOutOfRangeException(type, name, value, min, max);
    }

    /// <summary>
    /// Validates that a <see cref="byte"/> value is not greater than the specified maximum
    /// and throws an exception if it is.
    /// </summary>
    /// <remarks>
    /// The minimum is implicitly assumed to be <c>0</c>.
    /// </remarks>
    /// <param name="type">
    /// The <see cref="SqlDbType"/> associated with the value, used only in the exception message.
    /// </param>
    /// <param name="name">
    /// The parameter name associated with the value, used only in the exception message.
    /// </param>
    /// <param name="value">The value to test.</param>
    /// <param name="max">The inclusive maximum allowed value.</param>
    /// <exception cref="SqlTypeArgumentOutOfRangeException">
    /// Thrown when <paramref name="value"/> is greater than <paramref name="max"/>.
    /// </exception>
    private static void EnsureRange(SqlDbType type, string name, byte value, byte max)
    {
        if (value > max)
            throw new SqlTypeArgumentOutOfRangeException(type, name, value, 0, max);
    }

    /// <summary>
    /// Helper method to create a <see cref="SqlTypeDefinition"/> for <see cref="SqlDbType"/>s
    /// that accept a length argument.
    /// </summary>
    /// <param name="type">The <see cref="SqlDbType"/> being configured.</param>
    /// <param name="size">The size to assign, or <c>null</c> for no explicit size.</param>
    /// <param name="min">The inclusive minimum allowed size.</param>
    /// <param name="max">The inclusive maximum allowed size.</param>
    /// <returns>A new <see cref="SqlTypeDefinition"/> instance.</returns>
    private static SqlTypeDefinition WithSize(SqlDbType type, int? size, int min, int max)
    {
        string sizeAsString;
        if (size is not null)
        {
            sizeAsString = size.ToString() ?? string.Empty; //the compiler seems to think the preferred code: size.ToString() could return null. This is not the case.
            EnsureRange(type, nameof(size), size.Value, min, max);
        }
        else
        {
            sizeAsString = type switch
            {
                SqlDbType.VarBinary => "MAX",
                SqlDbType.NVarChar => "MAX",
                SqlDbType.VarChar => "MAX",
                SqlDbType.NChar => LIMIT_FOR_UNICODE.ToString(),
                SqlDbType.Char => LIMIT_FOR_ASCII.ToString(),
                SqlDbType.Binary => LIMIT_FOR_BYTE_ARRAY.ToString(),
                _ => string.Empty
            };
        }

        return new()
        {
            Type = type,
            Size = size,
            TypeDeclaration = $"{ToSql(type)}({sizeAsString})"
        };
    }

    /// <summary>
    /// Helper method to create a <see cref="SqlTypeDefinition"/> for <see cref="SqlDbType"/>s
    /// that do not take any precision, scale, or length arguments.
    /// </summary>
    /// <param name="type">The <see cref="SqlDbType"/> being configured.</param>
    /// <returns>A new <see cref="SqlTypeDefinition"/> instance.</returns>
    private static SqlTypeDefinition ByType(SqlDbType type) => new ()
    {
        Type = type,
        TypeDeclaration = ToSql(type)
    };

    /// <summary>
    /// Helper method to create a <see cref="SqlTypeDefinition"/> for <see cref="SqlDbType"/>s
    /// that support the <c>MAX</c> length modifier.
    /// </summary>
    /// <param name="type">The <see cref="SqlDbType"/> being configured.</param>
    /// <returns>A new <see cref="SqlTypeDefinition"/> instance.</returns>
    private static SqlTypeDefinition AsMax(SqlDbType type) => new()
    {
        Type = type,
        UseMax = true,
        TypeDeclaration = $"{ToSql(type)}(MAX)"
    };
    #endregion

    #region UniqueIdentifier
    /// <summary>
    /// Creates and returns a <see cref="SqlTypeDefinition"/> representing <see cref="SqlDbType.UniqueIdentifier"/>.
    /// </summary>
    public static SqlTypeDefinition AsUniqueIdentifier() =>
        ByType(SqlDbType.UniqueIdentifier);
    #endregion

    #region Chars

    /// <summary>
    /// Creates and returns a <see cref="SqlTypeDefinition"/> representing <see cref="SqlDbType.Char"/>.
    /// </summary>
    /// <param name="size">The length in characters, or <c>null</c> for no explicit size.</param>
    public static SqlTypeDefinition AsChar(int? size = null) =>
        WithSize(SqlDbType.Char, size, 1, LIMIT_FOR_ASCII);

    /// <summary>
    /// Creates and returns a <see cref="SqlTypeDefinition"/> representing <see cref="SqlDbType.NChar"/>.
    /// </summary>
    /// <param name="size">The length in characters, or <c>null</c> for no explicit size.</param>
    public static SqlTypeDefinition AsNChar(int? size = null) =>
        WithSize(SqlDbType.NChar, size, 1, LIMIT_FOR_UNICODE);

    /// <summary>
    /// <summary>
    /// Creates and returns a <see cref="SqlTypeDefinition"/> representing <see cref="SqlDbType.VarChar"/>.
    /// </summary>
    /// <param name="size">The length in characters, or <c>null</c> for no explicit size.</param>
    public static SqlTypeDefinition AsVarChar(int? size = null) =>
        WithSize(SqlDbType.VarChar, size, 1, LIMIT_FOR_ASCII);


    /// <summary>
    /// Creates and returns a <see cref="SqlTypeDefinition"/> representing <see cref="SqlDbType.NVarChar"/>.
    /// </summary>
    /// <param name="size">The length in characters, or <c>null</c> for no explicit size.</param>
    public static SqlTypeDefinition AsNVarChar(int? size = null) =>
        WithSize(SqlDbType.NVarChar, size, 1, LIMIT_FOR_UNICODE);

    /// <summary>
    /// Creates and returns a <see cref="SqlTypeDefinition"/> representing <c>VARCHAR(MAX)</c>.
    /// </summary>
    public static SqlTypeDefinition AsVarCharMax() =>
        AsMax(SqlDbType.VarChar);

    /// <summary>
    /// Creates and returns a <see cref="SqlTypeDefinition"/> representing <c>NVARCHAR(MAX)</c>.
    /// </summary>
    public static SqlTypeDefinition AsNVarCharMax() =>
        AsMax(SqlDbType.NVarChar);

    /// <summary>
    /// Creates and returns a <see cref="SqlTypeDefinition"/> representing <see cref="SqlDbType.Text"/>.
    /// </summary>
    /// <remarks>
    /// <see cref="SqlDbType.Text"/> is obsolete but preserved for legacy databases.
    /// <see cref="ObsoleteAttribute"/> is intentionally not used here.
    /// </remarks>
    public static SqlTypeDefinition AsText() =>
        ByType(SqlDbType.Text);

    /// <summary>
    /// Creates and returns a <see cref="SqlTypeDefinition"/> representing <see cref="SqlDbType.NText"/>.
    /// </summary>
    /// <remarks>
    /// <see cref="SqlDbType.NText"/> is obsolete but preserved for legacy databases.
    /// <see cref="ObsoleteAttribute"/> is intentionally not used here.
    /// </remarks>
    public static SqlTypeDefinition AsNText() =>
        ByType(SqlDbType.NText);

    //TODO: Document, unit test, code review
    public static SqlTypeDefinition AsCharOne() =>
        WithSize(SqlDbType.Char, 1, 1, LIMIT_FOR_ASCII);

    //TODO: Document, unit test, code review
    public static SqlTypeDefinition AsNCharOne() =>
        WithSize(SqlDbType.NChar, 1, 1, LIMIT_FOR_UNICODE);

    #endregion

    #region Binary

    /// <summary>
    /// Creates and returns a <see cref="SqlTypeDefinition"/> representing <see cref="SqlDbType.Binary"/>.
    /// </summary>
    /// <param name="size">The length in bytes, or <c>null</c> for no explicit size.</param>
    public static SqlTypeDefinition AsBinary(int? size = null) =>
        WithSize(SqlDbType.Binary, size, 1, LIMIT_FOR_BYTE_ARRAY);


    /// <summary>
    /// Creates and returns a <see cref="SqlTypeDefinition"/> representing <see cref="SqlDbType.VarBinary"/>.
    /// </summary>
    /// <param name="size">The length in bytes, or <c>null</c> for no explicit size.</param>
    public static SqlTypeDefinition AsVarBinary(int? size = null) =>
        WithSize(SqlDbType.VarBinary, size, 1, LIMIT_FOR_BYTE_ARRAY);

    /// <summary>
    /// Creates and returns a <see cref="SqlTypeDefinition"/> representing <c>VARBINARY(MAX)</c>.
    /// </summary>
    public static SqlTypeDefinition AsVarBinaryMax() =>
        AsMax(SqlDbType.VarBinary);

    /// <summary>
    /// Creates and returns a <see cref="SqlTypeDefinition"/> representing <see cref="SqlDbType.Image"/>.
    /// </summary>
    /// <remarks>
    /// <see cref="SqlDbType.Image"/> is obsolete but preserved for legacy databases.
    /// <see cref="ObsoleteAttribute"/> is intentionally not used here.
    /// </remarks>
    public static SqlTypeDefinition AsImage() =>
        ByType(SqlDbType.Image);
    #endregion

    #region Bit

    /// <summary>
    /// Creates and returns a <see cref="SqlTypeDefinition"/> representing <see cref="SqlDbType.Bit"/>.
    /// </summary>
    public static SqlTypeDefinition AsBit() =>
        ByType(SqlDbType.Bit);
    #endregion

    #region Integers

    /// <summary>
    /// Creates and returns a <see cref="SqlTypeDefinition"/> representing <see cref="SqlDbType.TinyInt"/>.
    /// </summary>
    public static SqlTypeDefinition AsTinyInt() =>
        ByType(SqlDbType.TinyInt);

    /// <summary>
    /// Creates and returns a <see cref="SqlTypeDefinition"/> representing <see cref="SqlDbType.SmallInt"/>.
    /// </summary>
    public static SqlTypeDefinition AsSmallInt() =>
        ByType(SqlDbType.SmallInt);

    /// <summary>
    /// Creates and returns a <see cref="SqlTypeDefinition"/> representing <see cref="SqlDbType.Int"/>.
    /// </summary>
    public static SqlTypeDefinition AsInt() =>
        ByType(SqlDbType.Int);

    /// <summary>
    /// Creates and returns a <see cref="SqlTypeDefinition"/> representing <see cref="SqlDbType.BigInt"/>.
    /// </summary>
    public static SqlTypeDefinition AsBigInt() =>
        ByType(SqlDbType.BigInt);
    #endregion

    #region Floating Point

    /// <summary>
    /// Creates and returns a <see cref="SqlTypeDefinition"/> representing <see cref="SqlDbType.Real"/>.
    /// </summary>
    public static SqlTypeDefinition AsReal() =>
        ByType(SqlDbType.Real);

    /// <summary>
    /// Creates and returns a <see cref="SqlTypeDefinition"/> representing <see cref="SqlDbType.Float"/>.
    /// </summary>
    /// <param name="precision">
    /// The floating-point precision, in bits, where 1–53 is valid. A value of <c>null</c>
    /// indicates the default precision.
    /// </param>
    /// <exception cref="SqlTypeArgumentOutOfRangeException">
    /// Thrown when <paramref name="precision"/> is less than 1 or greater than 53.
    /// </exception>
    public static SqlTypeDefinition AsFloat(byte? precision = null)
    {
        SqlDbType type = SqlDbType.Float;
        if (precision is not null && (precision < 1 || precision > 53))
            throw new SqlTypeArgumentOutOfRangeException(type, nameof(precision), precision.Value, 1, 53);
        return new SqlTypeDefinition()
        {
            Type = type,
            Precision = precision,
            TypeDeclaration = precision is not null ? $"{ToSql(type)}({precision})" : ToSql(type)
        };
    }
    #endregion

    #region decimal point

    /// <summary>
    /// Creates and returns a <see cref="SqlTypeDefinition"/> representing <see cref="SqlDbType.Decimal"/>
    /// with default precision and scale.
    /// </summary>
    public static SqlTypeDefinition AsDecimal() =>
        ByType(SqlDbType.Decimal);

    /// <summary>
    /// Creates and returns a <see cref="SqlTypeDefinition"/> representing <see cref="SqlDbType.Decimal"/>
    /// with the specified precision.
    /// </summary>
    /// <param name="precision">The total number of digits (1–38).</param>
    /// <exception cref="SqlTypeArgumentOutOfRangeException">
    /// Thrown when <paramref name="precision"/> is less than 1 or greater than 38.
    /// </exception>
    public static SqlTypeDefinition AsDecimal(byte precision)
    {
        SqlDbType type = SqlDbType.Decimal;

        EnsureRange(type, nameof(precision), precision, 1, 38);

        return new SqlTypeDefinition()
        {
            Type = type,
            Precision = precision,
            TypeDeclaration = $"{ToSql(type)}({precision})"
        };
    }

    /// <summary>
    /// Creates and returns a <see cref="SqlTypeDefinition"/> representing <see cref="SqlDbType.Decimal"/>
    /// with the specified precision and scale.
    /// </summary>
    /// <param name="precision">The total number of digits (1–38).</param>
    /// <param name="scale">
    /// The number of digits to the right of the decimal point. Must be less than or equal to <paramref name="precision"/>.
    /// </param>
    /// <exception cref="SqlTypeArgumentOutOfRangeException">
    /// Thrown when <paramref name="precision"/> or <paramref name="scale"/> is out of range,
    /// or when <paramref name="scale"/> is greater than <paramref name="precision"/>.
    /// </exception>
    public static SqlTypeDefinition AsDecimal(byte precision, byte scale)
    {
        SqlDbType type = SqlDbType.Decimal;

        EnsureRange(type, nameof(precision), precision, 1, 38);

        EnsureRange(type, nameof(scale), scale, precision);

        return new SqlTypeDefinition()
        {
            Type = type,
            Precision = precision,
            Scale = scale,
            TypeDeclaration = $"{ToSql(type)}({precision}, {scale})"
        };
    }

    /// <summary>
    /// Creates and returns a <see cref="SqlTypeDefinition"/> representing <see cref="SqlDbType.Money"/>.
    /// </summary>
    public static SqlTypeDefinition AsMoney() =>
        ByType(SqlDbType.Money);

    /// <summary>
    /// Creates and returns a <see cref="SqlTypeDefinition"/> representing <see cref="SqlDbType.SmallMoney"/>.
    /// </summary>
    public static SqlTypeDefinition AsSmallMoney() =>
        ByType(SqlDbType.SmallMoney);
    #endregion

    #region DateTime

    /// <summary>
    /// Creates and returns a <see cref="SqlTypeDefinition"/> representing <see cref="SqlDbType.DateTime2"/>.
    /// </summary>
    /// <param name="fractionalSecondPrecision">
    /// The fractional seconds precision (0–7). A value of <c>null</c> uses the default.
    /// </param>
    /// <exception cref="SqlTypeArgumentOutOfRangeException">
    /// Thrown when <paramref name="fractionalSecondPrecision"/> is greater than 7.
    /// </exception>
    public static SqlTypeDefinition AsDateTime2(byte? fractionalSecondPrecision = null)
    {
        SqlDbType type = SqlDbType.DateTime2;
        if (fractionalSecondPrecision is not null)
        {
            EnsureRange(type, nameof(fractionalSecondPrecision), fractionalSecondPrecision.Value, 7);
        }
        return new()
        {
            Type = type,
            Scale = fractionalSecondPrecision, //From what I can tell, in sql server it is called precision, but in ADO.Net you set scale.
            TypeDeclaration = fractionalSecondPrecision is not null ? $"{ToSql(type)}({fractionalSecondPrecision})" : ToSql(type)
        };
    }

    /// <summary>
    /// Creates and returns a <see cref="SqlTypeDefinition"/> representing <see cref="SqlDbType.DateTimeOffset"/>.
    /// </summary>
    /// <param name="fractionalSecondPrecision">
    /// The fractional seconds precision (0–7). A value of <c>null</c> uses the default.
    /// </param>
    /// <exception cref="SqlTypeArgumentOutOfRangeException">
    /// Thrown when <paramref name="fractionalSecondPrecision"/> is greater than 7.
    /// </exception>
    public static SqlTypeDefinition AsDateTimeOffset(byte? fractionalSecondPrecision = null)
    {
        SqlDbType type = SqlDbType.DateTimeOffset;
        if (fractionalSecondPrecision is not null)
        {
            EnsureRange(type, nameof(fractionalSecondPrecision), fractionalSecondPrecision.Value, 7);
        }
        return new()
        {
            Type = type,
            Scale = fractionalSecondPrecision, //From what I can tell, in sql server it is called precision, but in ADO.Net you set scale.
            TypeDeclaration = fractionalSecondPrecision is not null ? $"{ToSql(type)}({fractionalSecondPrecision})" : ToSql(type)
        };
    }

    /// <summary>
    /// Creates and returns a <see cref="SqlTypeDefinition"/> representing <see cref="SqlDbType.DateTime"/>.
    /// </summary>
    public static SqlTypeDefinition AsDateTime() =>
        ByType(SqlDbType.DateTime);

    /// <summary>
    /// Creates and returns a <see cref="SqlTypeDefinition"/> representing <see cref="SqlDbType.SmallDateTime"/>.
    /// </summary>
    public static SqlTypeDefinition AsSmallDateTime() =>
        ByType(SqlDbType.SmallDateTime);

    /// <summary>
    /// Creates and returns a <see cref="SqlTypeDefinition"/> representing <see cref="SqlDbType.Date"/>.
    /// </summary>
    public static SqlTypeDefinition AsDate() =>
        ByType(SqlDbType.Date);

    /// <summary>
    /// Creates and returns a <see cref="SqlTypeDefinition"/> representing <see cref="SqlDbType.Time"/>.
    /// </summary>
    /// <param name="fractionalSecondPrecision">
    /// The fractional seconds precision (0–7). A value of <c>null</c> uses the default.
    /// </param>
    /// <exception cref="SqlTypeArgumentOutOfRangeException">
    /// Thrown when <paramref name="fractionalSecondPrecision"/> is greater than 7.
    /// </exception>
    public static SqlTypeDefinition AsTime(byte? fractionalSecondPrecision = null)
    {
        SqlDbType type = SqlDbType.Time;
        if (fractionalSecondPrecision is not null)
        {
            EnsureRange(type, nameof(fractionalSecondPrecision), fractionalSecondPrecision.Value, 7);
        }
        return new()
        {
            Type = type,
            Scale = fractionalSecondPrecision, //From what I can tell, in sql server it is called precision, but in ADO.Net you set scale.
            TypeDeclaration = fractionalSecondPrecision is not null ? $"{ToSql(type)}({fractionalSecondPrecision})" : ToSql(type)
        };
    }
    #endregion

    /// <summary>
    /// Returns the default SQL Server type keyword for the provided <see cref="SqlDbType"/>,
    /// without any precision, scale, or length suffix.
    /// </summary>
    /// <param name="type">The <see cref="SqlDbType"/> value to convert.</param>
    /// <returns>The SQL Server type keyword as a string.</returns>
    /// <exception cref="SqlTypeNotSupportedException">
    /// Thrown when the specified <paramref name="type"/> is not supported by this implementation.
    /// </exception>
    public static string ToSql(SqlDbType type) => type switch
    {
        //Guid
        SqlDbType.UniqueIdentifier => "UNIQUEIDENTIFIER",

        //strings
        SqlDbType.NText => "NTEXT",
        SqlDbType.Text => "TEXT",
        SqlDbType.Char => "CHAR",
        SqlDbType.VarChar => "VARCHAR",
        SqlDbType.NVarChar => "NVARCHAR",
        SqlDbType.NChar => "NCHAR",

        //TODO: XML:Not supported yet. Add in the future after issues mapping resolved, or remove.
        //SqlDbType.Json => "NVARCHAR(MAX)", //NOTE: JSON is not currently a column type, it is most closely NVARCHAR(MAX)
        //SqlDbType.Xml => "NVARCHAR(MAX)", //currently uses .Net NVARCHAR(MAX)

        //byte[]
        SqlDbType.Binary => "BINARY",
        SqlDbType.Image => "IMAGE",
        SqlDbType.VarBinary => "VARBINARY",

        //bool
        SqlDbType.Bit => "BIT",

        //Integers
        SqlDbType.TinyInt => "TINYINT",
        SqlDbType.SmallInt => "SMALLINT",
        SqlDbType.Int => "INT",
        SqlDbType.BigInt => "BIGINT",

        //returns .Net float / double
        SqlDbType.Real => "REAL",
        SqlDbType.Float => "FLOAT",

        //returns .Net Decimals
        SqlDbType.Decimal => "DECIMAL",
        SqlDbType.Money => "MONEY",
        SqlDbType.SmallMoney => "SMALLMONEY",

        //returns .Net DateTime
        SqlDbType.DateTime => "DATETIME",
        SqlDbType.SmallDateTime => "SMALLDATETIME",
        SqlDbType.DateTime2 => "DATETIME2",
        SqlDbType.Date => "DATE",

        SqlDbType.Time => "TIME", //.Net TimeSpan
        SqlDbType.DateTimeOffset => "DATETIMEOFFSET",//.Net DateTimeOffset

        //.Net byte[]
        SqlDbType.Timestamp => "ROWVERSION",

        SqlDbType.Variant => "SQL_VARIANT", //.Net return type varies.

        SqlDbType.Udt => throw new SqlTypeNotSupportedException([type]),

        SqlDbType.Structured => throw new SqlTypeNotSupportedException([type]),
        _ => throw new SqlTypeNotSupportedException([type])
    };
}
